[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = "--version" # prevent Netlify npm install
[build]
  publish = "dist/practicas-angular"
  # command = "npm run build"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npm run build"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
